# Generated by Django 3.1.6 on 2021-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210606_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_run', models.IntegerField()),
            ],
        ),
    ]
