# Generated by Django 3.1.6 on 2021-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cricketscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketscore',
            name='run_perball',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
