# Generated by Django 3.1.6 on 2021-06-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cricketscore_run_perball'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketscore',
            name='playerballfirst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cricketscore',
            name='playerbatfirst',
            field=models.IntegerField(default=0),
        ),
    ]
