# Generated by Django 3.1.6 on 2021-06-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210610_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_perball', models.IntegerField()),
                ('Total_run', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_perball', models.IntegerField()),
                ('Total_run', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CricketScore',
        ),
    ]
