# Generated by Django 3.1.6 on 2021-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210610_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.IntegerField()),
                ('player2', models.IntegerField()),
            ],
        ),
    ]
