# Generated by Django 3.1.6 on 2021-06-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RPS',
            new_name='RPSModel',
        ),
    ]
